server:
  port: 8082
  use-forward-headers: true

logging:
  path: ./logs
  config: classpath:logback-spring.xml

swagger:
  show: true

spring:
  application:
    name: payne-baby
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
      enabled: true
      resolve-lazily: false

db:
  school:
    url: jdbc:mysql://127.0.0.1:3306/easy_edu?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  shop:
    url: jdbc:mysql://127.0.0.1:3306/shop_mall?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456